### ISSUE TITLE
Affirm checkout error when customer name contains apostrophes

### ISSUE THREAD

**Issue by modded-nate** [solidusio/solidus_affirm#42]
I'm not sure if this is more related to the extension or if it's more of an issue with Affirm but we had a customer reach out that they were receiving errors when clicking the Affirm payment option.

I recreated the user's cart exactly as he had it, and did in fact get an error that states "We encountered a problem with your checkout. The provided checkout total is invalid. Please contact the merchant to complete your purchase."

After trying a couple of things with the cart contents with no luck, I noticed that the user had an apostrophe at the end of their first name. Once I removed that, I was able to proceed to the Affirm portal.

![image](https://user-images.githubusercontent.com/21340562/66079623-678e1100-e532-11e9-8262-948dd0e4e6b0.png)

**Comment by modded-nate** [comment]
From Affirm support:

> Ah yes! We've seen that happen in the past as well

I asked if this was something addressed in their roadmap but haven't gotten a response yet. Just for fun I tested other special characters and none of the others I tested created the same error (e.g. 0, @, -, spaces)

**Comment by peterberkenbosch** [comment]
Will provide a PR for this that replaces or remove any apostrophes in customer name, or making sure we escape this so Affirm can handle it. 

est: 1h

**Comment by peterberkenbosch** [comment]
It looks like this is a parsing issue at Affirm. Looking at the logs when I send a name with an apostrophe it fails with:

```
RESPONSE BODY
{
  "code": "invalid_field",
  "status_code": 400,
  "field": "total",
  "ui": "redacted",
  "message": "The checkout total must be a positive integer: None",
  "type": "invalid_request"
}
```

**Comment by peterberkenbosch** [comment]
Update, this is not Affirm but the parsing of the json payload in the `data-affirm` attribute. Fixing in #59

**Comment by liquidia** [comment]
I still have this issue even after updating to 3.0.10 I am using Magento version 2.3.3
